### ISSUE TITLE
heroku database login failure

### ISSUE THREAD

**Issue by tkalevra** [MeLlamoPablo/schedulebot#32]
following directions from the heroku deployment guide

receiving db deploy login failure
{ error: password authentication failed for user "jfnbqhezghdzbj"
    at Connection.parseE (C:\Users\Christopher Thompson\schedulebot\node_modules\pg\lib\connection.js:569:11)
    at Connection.parseMessage (C:\Users\Christopher Thompson\schedulebot\node_modules\pg\lib\connection.js:396:17)
    at Socket.<anonymous> (C:\Users\Christopher Thompson\schedulebot\node_modules\pg\lib\connection.js:132:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
  name: 'error',
  length: 110,
  severity: 'FATAL',
  code: '28P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'auth.c',
  line: '307',
  routine: 'auth_failed' }

**Comment by MeLlamoPablo** [comment]
Hello, the standard version is unmaintained, see #29. That said, I'd be happy to help you solve the issue.

This appears to be a database connection failure. Go to your [Heroku dashboard](https://dashboard.heroku.com/apps), click on your app, then settings, and then `Reveal config vars`. You should have a `Database url` var. This contains your database credentials (do not post it on github). Then go to `Resources`, `Heroku Postgres` and make sure that the credentials are correct.

**Comment by tkalevra** [comment]
Thanks very much for getting back. I'll jump on and verify as soon as the wee ones are in bed. How far off (unmaintained is this)?


Sent from my Galaxy Tab A
-------- Original message --------From: Pablo Rodríguez <notifications@github.com> Date: 29/04/2017  5:49 p.m.  (GMT-04:00) To: MeLlamoPablo/schedulebot <schedulebot@noreply.github.com> Cc: tkalevra <ct8ball@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MeLlamoPablo/schedulebot] heroku database login failure (#32) 
Hello, the standard version is unmaintained, see #29. That said, I'd be happy to help you solve the issue.
This appears to be a database connection failure. Go to your Heroku dashboard, click on your app, then settings, and then Reveal config vars. You should have a Database url var. This contains your database credentials (do not post it on github). Then go to Resources, Heroku Postgres and make sure that the credentials are correct.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MeLlamoPablo/schedulebot","title":"MeLlamoPablo/schedulebot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MeLlamoPablo/schedulebot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MeLlamoPablo in #32: Hello, the standard version is unmaintained, see #29. That said, I'd be happy to help you solve the issue.\r\n\r\nThis appears to be a database connection failure. Go to your [Heroku dashboard](https://dashboard.heroku.com/apps), click on your app, then settings, and then `Reveal config vars`. You should have a `Database url` var. This contains your database credentials (do not post it on github). Then go to `Resources`, `Heroku Postgres` and make sure that the credentials are correct."}],"action":{"name":"View Issue","url":"https://github.com/MeLlamoPablo/schedulebot/issues/32#issuecomment-298193733"}}}

**Comment by tkalevra** [comment]
I've tried to simply use the dota deploy as it is far better maintained, however Im unsure the ability to simply ignore or lie in regard to various parts of this to ignore the dota aspects.

**Comment by MeLlamoPablo** [comment]
You could deploy the dota version and ignore the dota features. The only problem is that you'd need to create a Steam account for the bot, which is inconvenient. You can leave the rest of the settings to the default values.

**Comment by tkalevra** [comment]
I'll give it a go. Tyvm for the feedback. 


Sent from my Galaxy Tab A
-------- Original message --------From: Pablo Rodríguez <notifications@github.com> Date: 30/04/2017  7:25 a.m.  (GMT-04:00) To: MeLlamoPablo/schedulebot <schedulebot@noreply.github.com> Cc: tkalevra <ct8ball@gmail.com>, Author <author@noreply.github.com> Subject: Re: [MeLlamoPablo/schedulebot] heroku database login failure (#32) 
You could deploy the dota version and ignore the dota features. The only problem is that you'd need to create a Steam account for the bot, which is inconvenient. You can leave the rest of the settings to the default values.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/MeLlamoPablo/schedulebot","title":"MeLlamoPablo/schedulebot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/MeLlamoPablo/schedulebot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@MeLlamoPablo in #32: You could deploy the dota version and ignore the dota features. The only problem is that you'd need to create a Steam account for the bot, which is inconvenient. You can leave the rest of the settings to the default values."}],"action":{"name":"View Issue","url":"https://github.com/MeLlamoPablo/schedulebot/issues/32#issuecomment-298223941"}}}

**Comment by tkalevra** [comment]
I do have a steam account I was able to utilize, however receive this now

2017-04-29T23:53:02.491257+00:00 app[web.1]: npm ERR!     npm bugs schedulebot

2017-04-29T23:53:02.491515+00:00 app[web.1]: npm ERR! Or if that isn't available, you can get their info via:

2017-04-29T23:53:02.491745+00:00 app[web.1]: npm ERR!     npm owner ls schedulebot

2017-04-29T23:53:02.491971+00:00 app[web.1]: npm ERR! There is likely additional logging output above.

2017-04-29T23:53:02.546455+00:00 app[web.1]:

2017-04-29T23:53:02.546949+00:00 app[web.1]: npm ERR! Please include the following file with any support request:

2017-04-29T23:53:02.547239+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2017-04-29T23_53_02_497Z-debug.log

2017-04-29T23:53:02.677429+00:00 heroku[web.1]: Process exited with status 1

2017-04-29T23:53:02.642998+00:00 heroku[web.1]: State changed from up to down

2017-04-29T23:55:27.138630+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=dota-work-for-this.herokuapp.com request_id=1e0de750-18c2-4d16-adf5-327f229b20ce fwd="173.252.37.19" dyno= connect= service= status=503 bytes= protocol=https

2017-04-29T23:58:38.878671+00:00 heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=dota-work-for-this.herokuapp.com request_id=5f5994d7-30ca-4d85-8bce-25d58e18c77f fwd="173.252.37.19" dyno= connect= service= status=503 bytes= protocol=https

from the heroku log.

**Comment by MeLlamoPablo** [comment]
Sadly that part of the log doesn't tell me anything. This is a problem that I experienced with heroku: the web logs don't always show the full log. You can do two things here:

* Go to the resources tab and turn `bot` off. On another tab, open the logs, then turn the `bot` back on. If you're on the logs while the crash happens, you're gonna get the full log. But if you come thereafter, you might not get the full log, as it happened to you.
* Install the [heroku cli](https://devcenter.heroku.com/articles/heroku-cli) and type the following command: `heroku logs -a <your_app_name>`. That will bring the full log.

Again, sorry for the inconvenience.

**Comment by tkalevra** [comment]
I managed to get it going, wanted cc info even for the free one to start up, bit of a pain but I got that done and working. The question at this point is should the bot show as online? 
How do I reconfigure the bot in order to confirm settings, as visiting the https://<<app-name>>/herokuapp.com/# does not function to reconfigure. Once I am complete with my configuration and with your permission I will update the installation instructions in order to help others

**Comment by tkalevra** [comment]
here's the latest on re-deploy:

2017-05-01T13:46:52.440473+00:00 heroku[web.1]: State changed from starting to down

2017-05-01T13:46:52.482951+00:00 heroku[bot.1]: State changed from up to down

2017-05-01T13:46:53.176043+00:00 app[bot.1]: Couldn't shut down gracefully! A shutdown will be forced.

2017-05-01T13:46:53.176420+00:00 app[bot.1]: TypeError: Cannot read property 'close' of null

2017-05-01T13:46:53.176424+00:00 app[bot.1]:     at WebSocketManager.destroy (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:158:12)

2017-05-01T13:46:53.176425+00:00 app[bot.1]:     at ClientManager.destroy (/app/node_modules/discord.js/src/client/ClientManager.js:55:20)

2017-05-01T13:46:53.176426+00:00 app[bot.1]:     at Client.destroy (/app/node_modules/discord.js/src/client/Client.js:252:25)

2017-05-01T13:46:53.176426+00:00 app[bot.1]:     at Promise.all.then (/app/lib/index.js:410:20)

2017-05-01T13:46:53.166678+00:00 heroku[bot.1]: Stopping all processes with SIGTERM

2017-05-01T13:46:53.265193+00:00 heroku[bot.1]: Process exited with status 1

2017-05-01T13:46:55.669809+00:00 heroku[web.1]: Starting process with command `npm start`

2017-05-01T13:46:58.531513+00:00 app[web.1]: 

2017-05-01T13:46:58.531531+00:00 app[web.1]: > schedulebot@2.0.0 start /app

2017-05-01T13:46:58.531532+00:00 app[web.1]: > node ./setup/index.js

2017-05-01T13:46:58.531532+00:00 app[web.1]: 

2017-05-01T13:47:00.017944+00:00 app[web.1]: 

2017-05-01T13:47:00.121682+00:00 app[web.1]: The Setup server is live on port 36179

2017-05-01T13:47:01.555835+00:00 heroku[web.1]: Stopping all processes with SIGTERM

2017-05-01T13:47:01.761100+00:00 heroku[web.1]: Process exited with status 143

**Comment by MeLlamoPablo** [comment]
This still doesn't give me enough information. Can you please reach me on Discord? https://discord.gg/pVVsaDX
