### ISSUE TITLE
Cannot find module 'heroku-client'

### ISSUE THREAD

**Issue by jaafit** [MeLlamoPablo/schedulebot#45]
I'm installing on a namecheap server in their node v10 virtual environment.

npm run setup
npm WARN lifecycle The node binary used for scripts is /home/eatihgxc/nodevenv/eclipsediscord/10/bin/node but npm is using /opt/alt/alt-nodejs10/root/usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> schedulebot@2.0.0 setup /home/eatihgxc/eclipsediscord/schedulebot
> node ./setup/index.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'heroku-client'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/eatihgxc/eclipsediscord/schedulebot/setup/index.js:3:25)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! schedulebot@2.0.0 setup: `node ./setup/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the schedulebot@2.0.0 setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/eatihgxc/.npm/_logs/2021-01-04T14_08_02_044Z-debug.log

**Comment by MeLlamoPablo** [comment]
Hi! I'm sorry, I haven't been able to find time to maintain this project. It was a long time ago since I last looked at it but I'm sure that it's completely broken and the dependencies must be outdated or deprecated. The node-dota2 dependency doesn't seem to be actively maintained either so I'm not even sure if it's possible to make the dota2 stuff work at all.

This project was a nice learning experience but if I were to build it today I'd make very different decisions. I'm not sure if it's attempting to revive the project is worth the effort. But anyone is welcome to fork it and try :smile: 

Again, I'm very sorry for the inconvenience.
